server:
  port: 8888
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      datasource:
        master:
          username: Rock
          password: 1234qwer!@
          url: jdbc:sqlserver://172.16.90.12:1433;databasename=express_sunjuice
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        api:
          username: Rock
          password: 1234qwer!@
          url: jdbc:sqlserver://172.16.90.12:1433;databasename=APIServiceT
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


mybatis:
  config-location: classpath:mybatis.xml
debug: true


#配置日志

logging:
  level:
    #不同目录下的日志可配置不同级别
    com.express: debug
  #采用相对路径方式将日志文件输出到【log/myspringboot.log】
  file: log/myspringboot.log
  #采用绝对路径方式将日志文件输出到【/Users/wang/Downloads/myspringboot.log】
  #file: /Users/wang/Downloads/myspringboot.log


# 接口List长度
product:
  maxSize: 20
store:
  maxSize: 20
order:
  maxSize: 20

# token
jwt:
  secretKey: "SUN_JUICE"
  #   1000 * 60 * 60 * 24 = 86400000
  tokenOutTime: 86400000

# 众邮
zhongYou:
  v: "2.0"
  accessToken: "1b0c5e1c4ded4907bf59e8ec77fd4a26"
  appKey: "dc88920d82764c20b6b03e18fa45dbac"
  appSecret: "SUN_JUICE"
