server:
  port: 8888
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      datasource:
        master:
          username: Rock
          password: 1234qwer!@
          url: jdbc:sqlserver://172.16.90.12:1433;databasename=express_sunjuice
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        api:
          username: Rock
          password: 1234qwer!@
          url: jdbc:sqlserver://172.16.90.12:1433;databasename=APIServiceT
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


mybatis:
  config-location: classpath:mybatis.xml
debug: true



product:
  maxSize: 20
